### ISSUE TITLE
Mock SAS new feature requests

### ISSUE THREAD

**Issue by awaizkhan** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#1]
•	Version number (also part of URL) should be configuration driven rather than changing python file.
•	CBSD ID and Grant ID should be generated by Mock SAS rather than being driven by JSON files.

**Comment by awaizkhan** [comment]
needs verification.

**Comment by saudawar** [comment]
>>>Version number (also part of URL) should be configuration driven rather than changing python file.

Not fixed in MOCK SAS V2.1, so need to verify the same with MOCK SAS V3.0

>>>CBSD ID and Grant ID should be generated by Mock SAS rather than being driven by JSON files.

Verified in MOCK SAS V2.1, Mock SAS was generating CBSD ID and Grant ID by itself. No need of defining them in JSON files.

**Comment by awaizkhan** [comment]
@saudawar could you please update from latest Mock SAS testing?

**Comment by cwilliams-ericsson** [comment]
Done.  Closing
