### ISSUE TITLE
<pull 108>JSON structure for deregistration response in WINNF.FT.C.DRG.5.csv is incorrect

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#109]
JSON structure for deregistration response in WINNF.FT.C.RLQ.5 is incorrect	

	"deregistrationResponse" : 
				[
					{
					  "response": {
						 "responseCode": 103,
						 "responseData": "cbsdId"
					  }
					}
				]  
			}
}

As response data is list of strings. So data type need to be corrected.

**Comment by dgcell20** [comment]
I think you mean WINNF.FT.C.DRG.5 instead be WINNF.FT.C.RLQ.5?
I ask this as I see deregistrationResponse.

**Comment by pawan25062** [comment]
yes .. updated the same
