### ISSUE TITLE
Spectrum Inquiry Response JSON AFTER test finishes has wrong format of missing [

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#114]
Working with Release 1.0.0.1, after test finished (after questions section) the Airspan Domain Proxy kept sending Spectrum Inquiry Request to SAS Test Harness. The SAS Test Harness did reply with a "response code = 0" and a 5MHz channel (3.550-3.555 GHz). But the format of the JSON is wrong.
It has:
"availableChannel": {
        "channelType": "GAA",

where it should be:
"availableChannel": [
        {
          "channelType": "GAA",

During the test itself (BEFORE reaching the questions) the Spectrum Inquiry Response has correct format.
The wrong Spectrum Inquiry Response after test finished has little impact because the test finished anyway and CBSD/DP UUT needs to be moved back to UN-Registered state anyway.

**Comment by cwilliams-ericsson** [comment]
Opened branch "rel1.0.0.2_development" to hold this fix, and others which are candidates for a release 1.0.0.2.  For minor bug fixes, no new features planned.

**Comment by cwilliams-ericsson** [comment]
Addressed in release v1.0.0.2
