### ISSUE TITLE
PowerMeasTest has in Spectrum Inquiry Response "Channel Type" = PAL instead of GAA

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#115]
Executing the PowerMeasTest, the SAS Harness replies in Spectrum Inquiry Response that "channelType"= PAL instead of GAA (see log extract below). The following Grant Response in the PowerMeasTest does say correctly "channelType=GAA".
The JSON files in te SAS Harness in all the test cases are built to reply as GAA in order to cover the entire 3.55-3.7GHz frequency range and to avoid issues with the definition/configuration of PAL licenses in the CBSD/DP UUT.
"spectrumInquiryResponse": [
        {
            "availableChannel": [
                {
                    "channelType": "PAL", 
                    "frequencyRange": {
                        "highFrequency": 3560000000, 
                        "lowFrequency": 3550000000
                    },

**Comment by cwilliams-ericsson** [comment]
Addressed in rel1.0.0.2_development branch

**Comment by cwilliams-ericsson** [comment]
Addressed in release v1.0.0.2

**Comment by idanrazisr** [comment]
Issue still exists in SAS Harness release v1.0.0.2

**Comment by cwilliams-ericsson** [comment]
Missed one case in original fix.  Fixed in branch predev_1.0.0.3
