### ISSUE TITLE
RLQ and DRG test harness questions

### ISSUE THREAD

**Issue by dgcell20** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#119]
It has been brought to my attention the TS-0122 test specification and the test harness have some conflicting terminology:

For example, test specification step states:
A.	UUT stopped RF transmission at any time between triggering the relinquishment and UUT sending the relinquishment request

The script message for technician input states:
Did CBSD #1 UUT stop transmit upon sending Relinquishment Request?

The criteria of “between” indicates “after the trigger but before the request message” is sent by the CBSD. 
A specific vendor’s device may have its transmit shut down within a few seconds of the initiation of the trigger, but the actual relinquishment request message from the CBSD come later.
This indicates that the test is a “PASS” according to step 5, but the question seems to suggest that the relinquishment request message initiates the stop of TX which does not agree with the Pass/Fail criteria.

Should we change the  “upon” to “between the trigger and UUT sending the relinquishment request”?

I think it impacts these 12 cases:
     WINNF.FT.C.REG.7
     WINNF.FT.C.RLQ.1 - RLQ.6
     WINNF.FT.C.DRG.1 – DRG.5 (note: this would be “between the trigger and UUT sending the deregistration request or registration request”

**Comment by dgcell20** [comment]
[jsonUpdate.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1933285/jsonUpdate.zip)

This zip file contains 9 json files with recommended updates of text as follows:
For the RLQ test cases:
    Did CBSD1 stop RF transmissions between triggering the relinquishment and sending Relinquishment request?
    Did CBSD2 stop RF transmissions between triggering the relinquishment and sending Relinquishment request?

For DRG test cases:
    Did the CBSD stop RF transmissions between triggering the deregistration and sending a Deregistration or Registration request?

**Comment by dgcell20** [comment]
Clicked on the wrong button, did not wish have closed.

**Comment by awaizkhan** [comment]
Did the CBSD stop RF transmissions before receipt of Deregistration or Relinquishment request at Test Harness?

**Comment by dgcell20** [comment]
closed with v1.0.0.3
