### ISSUE TITLE
Failed on current version but ok on old Mock SAS version

### ISSUE THREAD

**Issue by gapelbaum** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#120]
Hi,

After installing the latest MOCK SAS , I receive the following response when I sends the registration requests https://XXXX:5000/v1.1/registration:
Response data: <title>404 Not Found</title>
Not Found

Actually, I copied the confing file and certificates from previous Mock SAS version (February 2018) , which worked fine, to the new Mock SAS version were I received the failure above.

I would appreciate  the responses.

**Comment by cwilliams-ericsson** [comment]
Hi,

We moved the protocol version to v1.2 some time ago.  If you can change the request message to:
https://XXXX:5000/v1.2/registration:
hopefully it should work for you.  If you want to check quickly whether this is the problem, change the version # in the Consts.py file.

**Comment by gapelbaum** [comment]
That was the problem, Thansk
