### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by gapelbaum** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#126]
Hi,

Test WINNF.FT.D.DRG.2 on step 3 expected to received a de-registration request from DP.

Does UUT should sent automatically (means without human actions) the de-registartion request after it send the Relinquishment request ?

If yes, please provide reasons based on specs.

Regards

**Comment by idanrazisr** [comment]
Hi,
this relates to issue #122. For all Deregistration Test Cases apearing in WINNF-TS-0122, step #2 of the Relinquishment message is optional. 
No issue in SAS Harness code here.
It depends on CBSD/DP UUT implementation if UUT just sends a De-Registration message or prior to the De-Registration message also a Relinquishment message is sent from UUT (optional based on implementation of UUT).

**Comment by awaizkhan** [comment]
Approved resolution provided in #122

**Comment by gapelbaum** [comment]
Closed
