### ISSUE TITLE
Mock SAS 2.1 is not initiating server even after providing correct csv file name

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#13]
Mock SAS 2.1 is not initiating server even after providing correct csv file name.
As current Mock SAS is checking json files defined in csv file. And Mock SAS is checking json file from wrong folder, which is leading to again asking for csv file as input.
Snapshot is attached for latest Mock SAS for your reference.
[Mock_SAS_2.1_snapshot.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1196820/Mock_SAS_2.1_snapshot.zip)

**Comment by awaizkhan** [comment]
Needs verification in V3.

**Comment by saudawar** [comment]
Yes, We will verify the same once V3 available on github.

**Comment by awaizkhan** [comment]
@saudawar please verify

**Comment by pawan25062** [comment]
Verified with latest Mock SAS. Issue resolved.
