### ISSUE TITLE
WINNF.FT.C.SCS.2 - CRL distribution issue

### ISSUE THREAD

**Issue by Bull1205** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#133]
Hi sir, 

Is the URL of CRL distribution point of "http://testharness.cbsd.winnf.com/crlserver.crl" available for WINNF.FT.C.SCS.2 testing? 
I have tried and found that the UUT cannot get the CRL list from this URL. It seems invalid and not accessible.

Thank you in advance.

**Comment by cwilliams-ericsson** [comment]
Hi,

For this test, the URL is intended to point to a local CRL or OCSP server set up by the test lab.  This also requires a local DNS server to associate the URL with the local server address.

More information is available in the WINNF CBSD/DP UUT Security Test Cases Tutorial, at:
http://www.wirelessinnovation.org/assets/winnf-in-00129-winnforum_cbsd_dp_uut_security_test_cases_tutorial_v_1_0_0_0.pdf
