### ISSUE TITLE
SAS Test Harness sends HTTP 302 instead of HTTP 400 Error

### ISSUE THREAD

**Issue by nmdeorankar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#137]
Hello,

Current test harness returns HTTP 302 on error with the format of the HTTP payload.  On redirecting to the url reply has mentioned which will ultimately query to SAS Server and gets reply with HTTP 400 Error.

But as per the specification(WINNF-TS-0016-V1.2.1) SAS Server should return HTTP 400 at the first place itself.

So my question is, what is the significance of the redirection here? and will SAS server respond in the same manner as test harness?.

Thanks,
-Navneet

**Comment by cwilliams-ericsson** [comment]
It would be interesting to see a Wireshark capture of the sequence of messages.

However, you should not infer any SAS behavior from this -- the Test Harness http error response are based on default Python libraries.  There has been no specific design intent to make http errors from the Test Harness line up with SAS behavior.

**Comment by nmdeorankar** [comment]
Thanks for you response. 

Even we thought the same.
