### ISSUE TITLE
"ERROR - the http request does not include key :  cbsdId " observed just after spectrum inquiry

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#14]
- Registration request and response successful between CBSD and Mock SAS 2.1

- "ERROR - the http request does not include key :  cbsdId " just after spectrum inquiry.

INFO: 08/03/2017 03:34:53 PM The final result of the test : WINNF.FT.C.SIQ.1 is - FAIL
INFO: 08/03/2017 03:34:56 PM the server shot down because :  ERROR - the http request does not include key :  cbsdId 

Mock SAS 2.1 log file is attached for your reference.

[_WINNF.FT.C.SIQ.1_2017_08_03_15_33_58.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1196837/_WINNF.FT.C.SIQ.1_2017_08_03_15_33_58.zip)

**Comment by awaizkhan** [comment]
Needs verification in V3.

**Comment by saudawar** [comment]
Yes, We will verify the same once V3 available on github.

**Comment by awaizkhan** [comment]
@saudawar please verify

**Comment by pawan25062** [comment]
Verified and issue resolved with latest Mock SAS. SI request and response both are successful.
