### ISSUE TITLE
The tool fails when measCapability in the registration message is empty string. 

### ISSUE THREAD

**Issue by BroderickJack** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#145]
According to WINNF-TS-0016-V1.2.5: _"If the measCapability parameter contains only the empty string (“”), the SAS assumes that the CBSD is not capable of reporting any measurement"_

Thus, I would believe that if that is the case the tool should not fail, however, I am getting this error from the tool:

`the server shot down because :  for the CBRS with the cbsdSerialNumber :D823956047 ERROR - loading optional parameters not succeededu'' is not one of [u'RECEIVED_POWER_WITHOUT_GRANT', u'RECEIVED_POWER_WITH_GRANT']
`

**Comment by cwilliams-ericsson** [comment]
See issue #139.  Internal WINNF discussions have settled on empty array [] rather than empty string [""].  WINNF-TS-0016 needs correction.  If you want an official WINNForum response, please contact WINNForum directly.

**Comment by BroderickJack** [comment]
Great, thank you for the response.
