### ISSUE TITLE
radioTechnology JSON validator outdated

### ISSUE THREAD

**Issue by mjmlopes** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#146]
Hello all.
As seen on some JSON files, the radioTechnology only has two valid values:

```
"radioTechnology":{"$or":["E_UTRA","CAMBIUM_NETWORKS"]}
```
Can this be updated to the values defined in the WINNF-SSC-0002 v9.0.0 (10 February 2021), section 6?

Thanks.

**Comment by dgcell20** [comment]
It was understood that new radioTechnology values would be introduced over time.  To keep from making updates to the build for each air interface, the harness allows the user to update an XML file.
Section 10 of WINNF-IN-0156 describes several XML files for the user to supply input parameters for the test environment configuration. More specifically, section 10.4 discusses the XML configuration file for the CBSD air interface options.
The user can update the radioTechnology field with the additional air interface that is needed.
For example, to add NR air interface.
"radioTechnology":{"$or":["E_UTRA","CAMBIUM_NETWORKS", "NR"]}

**Comment by mjmlopes** [comment]
Ok, I thought that it was only necessary to change the laterDefindedOptional.json file and not all of the 8 other files where the OR check is present. So it seems that the section 10.4 is incomplete since by following it, the user will have some tests failing without knowing why (e.g. WINNF.FT.C.REG.3_waiver) while others pass (e.g. WINNF.FT.C.REG.8). Actually, I don't understand why some files have a definition for what radioTechnology should have while a default file exists with the same information.
Thanks for the information and I'll change the other 8 files.
