### ISSUE TITLE
Mock-SASv2.1: The contents setting of registrationOprional.json is not correctly

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#16]
The contents setting of installationParam in latest Mock-SASv2.1 is not correctly. the original file is below and it is not working.

Original:
{
    "name":"WINNF.FT.C.SIQ.1_001",  
			"registrationOptionalParams":
        	[
            	{
				  "callSign":"${maximumLength:128}",
				  "horizontalAccuracy":"${range:0To50}",
				  "verticalAccuracy":"${range:0To3}",
				  "antennaAzimuth":"${range:0To360}",
				  "antennaDowntilt":"${range:-90To90}",
				  "eirpCapability":"${range:-127To47}",
				  "antennaBeamwidth":"${range:0To360}",
				  "antennaModel":"${maximumLength:128}",
				  "groupingParam": { "groupId": "${maximumLength:128}", "groupType": "INTERFERENCE_COORDINATION" },
				  "CpiSignatureData":{"protectedHeader": "${maximumLength:128}","encodedCpiSignedData": "${maximumLength:128}","digitalSignature": "${maximumLength:128}"},
				  "cbsdInfo":{"firmwareVersion": "${maximumLength:64}","hardwareVersion": "${maximumLength:64}","model": "${maximumLength:64}","softwareVersion": "${maximumLength:64}","vendor": "${maximumLength:64}"}
				}
			]	
}

It should be changed to:
{
    "name":"WINNF.FT.C.SIQ.1_001",  
			"registrationOptionalParams":
        	[
            	{				  
				  "callSign":"${maximumLength:128}",
				  "airInterface": { "radioTechnology": "E_UTRA", "supportedSpec": "FFS" },
				  "cbsdCategory": {"$or":["A","B"]},
				  "measCapability":  {"$or":[["EUTRA_CARRIER_RSSI_NON_TX"],["EUTRA_CARRIER_RSSI_ALWAYS"]]},
				  "installationParam":{
					  "latitude": "${range:-90.00000To90.00000}",
					  "longitude": "${range:-180.000000To180.000000}",
					  "height": "${range:0To300}",
					  "heightType": {"$or":["AGL","AMSL"]},
					  "horizontalAccuracy":"${range:0To50}",
					  "verticalAccuracy":"${range:0To3}",
					  "indoorDeployment":{"$or":["True","False"]},
					  "antennaAzimuth":"${range:0To360}",
					  "antennaDowntilt":"${range:-90To90}",
					  "antennaGain":"${range:-127To128}",
					  "eirpCapability":"${range:-127To47}",
					  "antennaBeamwidth":"${range:0To360}"},
				  "groupingParam": { "groupId": "${maximumLength:128}", "groupType": "INTERFERENCE_COORDINATION" },
				  "CpiSignatureData":{"protectedHeader": "${maximumLength:128}","encodedCpiSignedData": "${maximumLength:128}","digitalSignature": "${maximumLength:128}"},
				  "cbsdInfo":{"firmwareVersion": "${maximumLength:64}","hardwareVersion": "${maximumLength:64}","model": "${maximumLength:64}","softwareVersion": "${maximumLength:64}","vendor": "${maximumLength:64}"}

				}
			]	
}

**Comment by awaizkhan** [comment]
Need to update the example jason. Idan to update.

**Comment by ericzh31ericsson** [comment]
The file is still not in correct format in Mock-SAS v3.0. Has to changed accordingly.

**Comment by ericzh31ericsson** [comment]
Open a new issue for Mock-SAS v3.0
