### ISSUE TITLE
Mock-SASv2.1: Assert.py code change to support the flexibility of processing add_Json_Optional_Parameters

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#17]
In current v2.1 Mock-SAS, it has the limitation of adding optional parameters if the parameter has "multiple json objects" inside. The limitation is that the number/name of these requested  "multiple json objects" in the incoming request message has to be exactly same as the files in OptionalParams folder. If there is any parameter missing, the test would be failed. But the CBSD may not include all the conditional/Optional parameters in such as cbsdInfo, installationParam or others.

I modified some code in my system and it is more flexible to adding Optional Parameters when the incoming message not having full list of optional/conditional parameters.

**The code changes are below:**
in **Assert.py, "def add_Json_Optional_Parameters(self,expected,httpRequest,suffix):"**, the new codes are:

        for key, value in optional.iteritems() :
            d = collections.OrderedDict()         
            if key not in expected[0]:
                if key in httpRequest:
                    if(not self.isThereMoreThenOneValueInside(value)):
                        JsonComparisonUtils.ordered_dict_prepend(expected[0], key, value)   
                    else:## key not exists at all
                        self.dontCheckNode.append(key)  
                        for key2 in optional[key]:
                            if key2 in httpRequest[key]:    # added by Eric                       
                                result = JsonComparisonUtils._are_same(optional[key][key2], httpRequest[key][key2],False)
                                if False in result:
                                    raise Exception("ERROR - there is an validation error between http request and the optional parameter json") 

**The original codes are:**

        ### check if the key is optional means its not in the expected json but it is in the requests and its allowed in the protocol      
        for key, value in optional.iteritems() :
            d = collections.OrderedDict()         
            if key not in expected[0]:
                if key in httpRequest:
                    if(not self.isThereMoreThenOneValueInside(value)):
                        JsonComparisonUtils.ordered_dict_prepend(expected[0], key, value)   
                    else:## key not exists at all
                        self.dontCheckNode.append(key)  
                        for key2 in optional[key]:                           
                            result = JsonComparisonUtils._are_same(optional[key][key2], httpRequest[key][key2],False)
                            if False in result:
                                raise Exception("ERROR - there is an validation error between http request and the optional parameter json")

**Comment by awaizkhan** [comment]
To be verified in V3.

**Comment by ericzh31ericsson** [comment]
closed in V3.0
