### ISSUE TITLE
HTTP version mismatch issue

### ISSUE THREAD

**Issue by awaizkhan** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#2]
MOCK SAS V2 does not provide correct HTTP version

**Comment by pczeremuga** [comment]
Mock_SAS v2 responds with incorrect HTTP protocol version: HTTP/1.0 200 OK.  However, the HTTP response should include HTTP/1.1 version.

A temporary workaround was implemented by modifying function of runFlaskServer in cbrsPython\model\flaskServer.py:
def runFlaskServer(host,port,ctx):
    from werkzeug.serving import WSGIRequestHandler
    WSGIRequestHandler.protocol_version = "HTTP/1.1"
    app.run(host,port,threaded=True,ssl_context=ctx, request_handler=WSGIRequestHandler)

Issue was observed and reproduced using Nokiad CBSD.

**Comment by idanrazisr** [comment]
This issue is fixed as part of the CBRS_Mock_SAS_Python_Master uploaded on August 2nd 2017

**Comment by cwilliams-ericsson** [comment]
Done.  Closing
