### ISSUE TITLE
Mock-SASv2.1: the name fix for the logs in LogsPerTest folder

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#21]
The log name for the log in LogsPerTest folder has "_" in front of log name. I made a change in Loggers\DebugLogger.py to remove the "_" in front of the log name.

The code change is in DeDebugger.py line 17. The new code is:

            log_file =  '\\Logs\\LogsPerTest\\'+log_Name+"_" + str(datetime.now().strftime("%Y_%m_%d_%H_%M_%S")) +'.log' 

The original one is:

            log_file =  '\Logs\LogsPerTest\_'+log_Name+"_" + str(datetime.now().strftime("%Y_%m_%d_%H_%M_%S")) +'.log'

After change the log name becomes the format below:
WINNF.FT.C.REG.1_2017_08_04_13_48_02.log

**Comment by awaizkhan** [comment]
Fixed needs verification. E/// to verify in V3.
