### ISSUE TITLE
Mock-SASv2.1: The measurement report algorithm is not suitable to the hearbeat test

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#22]
In current heartbeat test, if the json file is heartbeat repeatsAllowed = true, and no measurement report in the heartbeat request message, then the test will be failed due to no measurement report in 5 heartbeat request. the error message is below:

_the server shot down because :  ERROR - no meas report received in the last 5 heart beats request
10.45.16.207 - - [04/Aug/2017 15:51:20] "POST /shutdown?validationMessage=ERROR+-+no+meas+report+received+in+the+last+5+heart+beats+request HTTP/1.1" 400 -_

The failure reason is that in the code, if repeatsAllowed = true, it will check the measurement report key word from the incoming heartbeat request message, if no such information in five heartbeat request messages, it will fail the test anyway.

But the measurement report is Conditional Parameters, it could not be included in the message. So current solution can't handle the case properly.

Also in the code the key word used for checking measurement report is "measReportConfig", which is not correct. In the spec the parameter name should be "measReport".

Ideally to handle measurement report properly, Mock-SAS should only check measurement report when previous response messages have measReportConfig set. 

Also current code can only check if there is measurement report key word exist, no value check.

Also I have little bit confused to the usage of following code in CBRSRequestHandler.py:

        if(typeOfCalling==consts.HEART_BEAT_SUFFIX_HTTP):
            if(self.assertion.is_Json_Request_Contains_Key( req, "measReportConfig")):
                del req["measReportConfig"]

**Comment by awaizkhan** [comment]
E/// to continue development as V3 will not support all aspects requested in the ticket.

**Comment by idanrazisr** [comment]
Mock-SAS code uploaded to github 1-September removed the implementation of Measurment Report for 5 hearbeats.
Mock-SAS code uploaded 1-September-2017 addresses Meas Reports according to section 11.9 in Mock-SAS tutorial “Handling of measReport in Request Messages”.
