### ISSUE TITLE
<MOCK SAS V3.0 Demo> Mock SAS should not increment "Transmit Expire" time after getting error code in HB response

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#23]
As per yesterday's demo on MOCK SAS V3.0, Mock SAS was incrementing "Transmit Expire" time in every HB response.And as discussed, Mock SAS should not increment "Transmit Expire" time after getting error code in HB response.

**Comment by idanrazisr** [comment]
issue resolved as part of Mock-SAS updates uploaded 16-Aug-2017

**Comment by awaizkhan** [comment]
@saudawar please update ...

**Comment by pawan25062** [comment]
issue resolved in latest branch for mock-sas.
