### ISSUE TITLE
<MOCK SAS V3.0 Demo> Grant Expiry time should not be hard-coded and shall be handled similar to transmitExpiryTime

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#24]
As per yesterday's demo on MOCK SAS V3.0, Grant Expiry time was hard-coded in xml files at CBRSConf folder. It will be a good option if Grant Expiry time can be handled similar to transmitExpiryTime, so that "grant renew as true" case can be handled correctly where MOCK SAS need to send a new time for Grant Expiry time.

**Comment by idanrazisr** [comment]
Issue resolved as patyt of Mock-SAS updates uploaded 16-Aug-2017

**Comment by idanrazisr** [comment]
Mock-SAS code uploaded 1-September-2017 addresses this according to section 11.7 in Mock-SAS tutorial “Handling of Grant Expiry Time, Transmission Expiry Time and Grant Renew”.

**Comment by awaizkhan** [comment]
@saudawar please update

**Comment by pawan25062** [comment]
Verified. Now grant expiry is handled same as transmitExpiry with latest Mock SAS version.
