### ISSUE TITLE
<MOCK SAS V3.0 Demo> Parameters of type list should have handling of expecting variable length

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#25]
Parameters of type list should have handling of expecting variable length, so that we need not to define them one by one( for example measReport object in SI, GRANT or HB requests)

**Comment by awaizkhan** [comment]
@idanrazisr could you please update

**Comment by pawan25062** [comment]
issue is resolved in latest releases of mock-sas.
