### ISSUE TITLE
<MOCK SAS V3.0 Demo> Handling of optional procedures (SI, Relinquishment) in CSV file

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#27]
As per yesterday's demo on MOCK SAS V3.0, handling of optional procedures(SI, Relinquishment) in CSV file, so that it won't fail if we do not define them in CSV file and CBSD sends requests for the same.
It will be good if optional procedures can be handled like optional parameters, so that test case will not fail due to different implementation of these procedures(SI, relinquishment) from different vendors.

**Comment by idanrazisr** [comment]
Relinquishment addressed as part of Mock-SAS updates uploaded 16-Aug-2017.
If Relinquishment Request comes before De-registration Request then Mock-SAS engine will treat it according to rel_In_Case_Of_Deregistration.json in the json expected folder

**Comment by idanrazisr** [comment]
Mock-SAS code uploaded 1-September-2017 addresses this according to section 11.5 in Mock-SAS tutorial “First Spectrum Inquiry Request as an Optional Procedure in the Test Sequence” and section 11.6 in Mock-SAS tutorial “Relinquishment Request as an Optional Procedure in the Test Sequence”.

**Comment by awaizkhan** [comment]
@saudawar please update
