### ISSUE TITLE
<MOCK SAS V3.0 Demo> grantRenew flag should be handled in HB request messages

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#28]
As per yesterday's demo on MOCK SAS V3.0, HB request was shown as "grant renew:false" and grant expire time was fixed from xml file defined in CBRSConf folder. And as discussed, Mock SAS should increment "grant expire" time after grant renew as true in HB request.  It was missing in V3.0 as there was no parameter defined for adding value to new grant expire time same as for transmit expire time.

**Comment by idanrazisr** [comment]
Issue solved as part of Mock-SAS updates uploaded 16-Aug-2017

**Comment by idanrazisr** [comment]
Mock-SAS code uploaded 1-September-2017 addresses this according to section 11.7 in Mock-SAS tutorial “Handling of Grant Expiry Time, Transmission Expiry Time and Grant Renew”.

**Comment by awaizkhan** [comment]
@saudawar please update

**Comment by ericzh31ericsson** [comment]
Please verify again with the new branch submitted by Ericsson in Oct. 20th
