### ISSUE TITLE
Mock-SAS handling of X.509 certificates with Winnforum extensions

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#29]
Mock-SAS is based on Python 2.7. Python 2.7 has its own SSL implementation which is Python27\Lib\ssl.py.
Winnforum has speciifc requirements for X.509 certificates for SAS and CBSD which include new OIDs 1.3.6.1.4.1.46609.X.
In https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/issues/new it is explained how to implement this OIDs in Linux openssl.cnf so the Linux will recognize these OIDs.
Currently in the Python SSL implementation we did not find a way to implement these new OIDs so Mock-SAS fails to establish the TLS connection if the 1.3.6.1.4.1.46609.X are present in the X.509 certificates.

**Comment by awaizkhan** [comment]
@idanrazisr i'm assigning this to you; may be as verification for pull #44 you can verify this?

**Comment by saudawar** [comment]
The code has been modified in the Critical_Extension_Branch and sent sent for review to be merged in master branch.

**Comment by idanrazisr** [comment]
Following the readme_file_x509_RSA_certs_test_labs file in the SAS Harness release, there is no need for Mock-SAS to handle X.509 certificates with Winnforum extensions as critical OIDs. Closing issue.
