### ISSUE TITLE
Additional issues with V2 Mocks SAS

### ISSUE THREAD

**Issue by awaizkhan** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#3]
1)      Mock SAS is not accepting optional parameters from registrationOptional.json  defined for “installationParam” object. When registration request comes with optional parameter(horizontal accuracy/vertical accuracy/EIRP Capability/antenna Model) in installationParam object,  MOCK SAS marking test case as fail with following error:
               INFO: 07/12/2017 01:39:19 PM the server shot down because :  for the CBRS with the cbsdSerialNumber :401629000040 ERROR - An Error occurred while comparing between actual and expected requestin the json : nmstest_registration1.json
2)      Mock SAS handling for "groupingParam" object. As "groupingParam" object can contain array of data objects. According to v2.0 SAS  to CBSD technical spec:
 
3)      Test code for SI updated with 10MHz per measurement reports. But according “WINNF-17-SSC-0002” permitted enumeration defined as follows:

 
So CBSD may use 5MHz per measurement report. 
4)      In case of deregistraion request(MOCK SAS is adding extra parameters fccId and userId for comparing results):
Expected:
{
      "cbsdId": "ruckus1cbsdSerialNumber401629000040", 
      "fccId": "S9GQ710US01IIIIIIII", 
      "userId": "Aricent241"
  }
Actual:
  {
      "cbsdId": "ruckus1cbsdSerialNumber401629000040"
  }
5)      While testing the DP test code with Mock SAS, Mock SAS is not reading the complete serial number for the second CBSD ID in the spectrum inquiry request. Although the registration procedure got through
INFO: 07/13/2017 03:17:00 PM The final result of the test : dp is - FAIL
INFO: 07/13/2017 03:17:02 PM the server shot down because :  ERROR - there is no cbrs obj registered with the cbsdSerialNumber :  01629000040

6)      MOCK SAS handling regarding grantExpireTime and transmitExpireTime

Files attached herewith mail:
•         InstallationParam.log
o   Log file for issue 1
•         _dereg_2017_07_05_15_41_56
o   Log file for issue 4
•         _dp_2017_07_13_15_16_30 and dp.csv
o   Log file for issue 5

**Comment by saudawar** [comment]
CSV files and logs are attached for issue 1, 4 and 5

[logs_and_csv.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1158334/logs_and_csv.zip)

**Comment by idanrazisr** [comment]
This issue is fixed as part of the CBRS_Mock_SAS_Python_Master uploaded on August 2nd 2017

**Comment by awaizkhan** [comment]
Please verify the fix.

**Comment by saudawar** [comment]
Need to verify the same with MOCK SAS V3.0

**Comment by awaizkhan** [comment]
@saudawar could you please verify this in latest version?
