### ISSUE TITLE
SAS URL is in correct - MOCK SAS response reject the URL "https://XXXXXXXXX:5000/v2.0/registration/"

### ISSUE THREAD

**Issue by meitalk** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#30]
I uploaded the updates from the 16/8/2017. My flaskServer.py file contained the fix of the SAS version, i.e "@app.route("/v2.0/<typeOfCalling>",methods=['POST'])". I also tried to add double '//' in the SAS version  yet the error "/v2.0//<typeOfCalling>", as was suggested in Idan's comment #12.

The error below continue to appear:
 RedirectStrategy::isRedirected=false
SAS Response status is 404: NOT FOUND
 SAS Response data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>404 Not Found</title><h1>Not Found</h1><p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

**Comment by idanrazisr** [comment]
The file "with_end_slash_flaskServer.py" is for CBSDs that still have an end slash after the "method". For example HTTP://<SAS-URL>/v2.0/registration/  where the latest Winnforum SAS<->CBSD protocol spec states it should be without the end slash HTTP://<SAS-URL>/v2.0/registration. 
It is just an example file.
It is possible to edit this and add/remove the end slash in the flaskServer.py itself in line 20

**Comment by awaizkhan** [comment]
@meitalk could you please verify?

**Comment by cwilliams-ericsson** [comment]
No longer an issue.  Closing.
