### ISSUE TITLE
Mock-SASv3.0: The contents setting of registrationOprional.json is not correctly

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#31]
In Mock-SAS v3.0 the format of  registrationOprional.json is still not correctly. Correct one should be like below.

{
      "name":"registrationOptionalParams",  
			"registrationOptionalParams":
        	[
            	{				  
				  "callSign":"${maximumLength:128}",
				  "airInterface": { "radioTechnology": "E_UTRA", "supportedSpec": "FFS" },
				  "cbsdCategory": {"$or":["A","B"]},
				  "measCapability":  {"$or":[["EUTRA_CARRIER_RSSI_NON_TX"],["EUTRA_CARRIER_RSSI_ALWAYS"],["EUTRA_CARRIER_RSSI_NON_TX", "EUTRA_CARRIER_RSSI_ALWAYS"] ]},
				  "installationParam":{
					  "latitude": "${range:-90.00000To90.00000}",
					  "longitude": "${range:-180.000000To180.000000}",
					  "height": "${range:0To300}",
					  "heightType": {"$or":["AGL","AMSL"]},
					  "horizontalAccuracy":"${range:0To50}",
					  "verticalAccuracy":"${range:0To3}",
					  "indoorDeployment":{"$or":["True","False"]},
					  "antennaAzimuth":"${range:0To360}",
					  "antennaDowntilt":"${range:-90To90}",
					  "antennaGain":"${range:-127To128}",
					  "eirpCapability":"${range:-127To47}",
					  "antennaBeamwidth":"${range:0To360}"},
				  "groupingParam": { "groupId": "${maximumLength:128}", "groupType": "INTERFERENCE_COORDINATION" },
				  "CpiSignatureData":{"protectedHeader": "${maximumLength:128}","encodedCpiSignedData": "${maximumLength:128}","digitalSignature": "${maximumLength:128}"},
				  "cbsdInfo":{"firmwareVersion": "${maximumLength:64}","hardwareVersion": "${maximumLength:64}","model": "${maximumLength:64}","softwareVersion": "${maximumLength:64}","vendor": "${maximumLength:64}"}

				}
			]	
}

**Comment by idanrazisr** [comment]
Mock-SAS code uploaded 1-September-2017 has a new set of "JSON Optional" files. I will review again based on what you wrote here for Registration "JSON Optional".

**Comment by idanrazisr** [comment]
Mock-SAS code uploaded 8-September-2017 has a new set of "JSON Optional" files.
