### ISSUE TITLE
Mock-SAS v3.0: The function "def isThereMoreThenOneValueInside(self,value):" in Assert.py is not working properly

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#32]
Still the code below is not understandable. At lease it doesn't work for the case of "measCapability":  {"$or":[["EUTRA_CARRIER_RSSI_NON_TX"],["EUTRA_CARRIER_RSSI_ALWAYS"],["EUTRA_CARRIER_RSSI_NON_TX", "EUTRA_CARRIER_RSSI_ALWAYS"] ]}, and this could be included in the real message.

    def isThereMoreThenOneValueInside(self,value):
        numberOfValues = 0
        if("$or" in str(value)):
            print str(value)
            strValue = str(value)
            indexOfStartOfOrSentence = strValue.index("$or")-2
            newStr = strValue[indexOfStartOfOrSentence:]
            indexOfEndBreckets = newStr.index("}")
            if(newStr[indexOfEndBreckets+1]!=None):
                return True                 

To make the code pass, I just simply change the code to:

     def isThereMoreThenOneValueInside(self,value):
        numberOfValues = 0
        if("$or" in str(value)):

And also there is more code changes to make this change work. The detail will be in other new issue tickets.

**Comment by ericzh31** [comment]
sorry the updated code should be:

def isThereMoreThenOneValueInside(self,value):
    numberOfValues = 0
    if("$or" in str(value)):
            return True

**Comment by idanrazisr** [comment]
This code was entered as a comment to the Assert.py file for code uploaded to github September 6th
