### ISSUE TITLE
Mock-SAS v3.0: Code changes in Assert.py/def add_Json_Optional_Parameters(self,expected,httpRequest,suffix):

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#33]
To make the adding Optional Parameters work properly in the case of "$or", I did some code changes in this function. The changes detail is below:

        for key, value in optional.iteritems() :
            d = collections.OrderedDict()         
            if key not in expected[0]:
                if key in httpRequest:
                    if(not self.isThereMoreThenOneValueInside(value)):
                        JsonComparisonUtils.ordered_dict_prepend(expected[0], key, value)   
                    else:
                        '''
                        Eric did some changes
                        '''                       
                        if "$or" in optional[key]:
                            self.dontCheckNode.append(key)
                            result = JsonComparisonUtils._are_same(optional[key], httpRequest[key],False)
                            if False in result:
                                raise Exception("ERROR - there is an validation error between http request and the optional parameter json")                          
                        else:
                            self.dontCheckNode.append(key)
                            for key2 in optional[key]:
                                print optional[key]   
                                if key2 in httpRequest[key]:                        
                                    result = JsonComparisonUtils._are_same(optional[key][key2], httpRequest[key][key2],False)
                                    if False in result:
                                        raise Exception("ERROR - there is an validation error between http request and the optional parameter json") 
                                    
                            '''
                            The changes Eric made is end here
                            '''

**Comment by idanrazisr** [comment]
Mock-SAS code implementation uploaded to github 1-September has a completly new implementation for this section.

**Comment by ericzh31ericsson** [comment]
have been done in the new branch submitted by Ericsson in Oct. 20th
