### ISSUE TITLE
Mock-SAS v3.0: Code change in JsonComparisonUtils.py

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#34]
There could be a bug in JsonComparisonUtils.py. It is in the line 229, function def validate_Json_Value_Special_Sign(expected,actual):. 

The original code is:

if strExpectedOnlyLetters.upper() == strAcutal.upper():

But I think it should be 

if strExpectedOnlyLetters.upper() == strActualOnlyLetters.upper():

**Comment by idanrazisr** [comment]
Mock-SAS code implementation uploaded to github 6-September has this in a comment for future testing.

**Comment by ericzh31ericsson** [comment]
have been done in the new branch submitted by Ericsson in Oct. 20th
