### ISSUE TITLE
Mock-SAS v3.0: Not a good solution to add optional parameters in CBRSConf/cbsdc1.xml

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#35]
In Mock-SAS v3.0 I found that some optional parameters are added to CBRSConf/cbsdc1.xml file, such as 
cbsdCategory and airInterface. 

This could make test engineer more confused. After the code changes in my previous four issues (issue 31.32.33.34) , these parameters can be removed from CBRSConf file and added back to the folder of OptionalParams.

**Comment by idanrazisr** [comment]
Mock-SAS code uploaded 1-September-2017 addresses this and has only a few parameters without ranges. Eventually Winnforum will need to give a well defined template to the cbsdc1.xml to be filled without ranges.
