### ISSUE TITLE
Mock-SAS v3.0: Not sure what the function is of program model.with_final_slash_flaskServer.py

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#36]
In Mock-SAS v3.0 there is a new function "model.with_final_slash_flaskServer.py", But I couldn't find how and where the function is called. Could anyone provide some detail information?

**Comment by idanrazisr** [comment]
The file "with_end_slash_flaskServer.py" is for CBSDs that still have an end slash after the "method". For example HTTP://<SAS-URL>/v2.0/registration/  where the latest Winnforum SAS<->CBSD protocol spec states it should be without the end slash HTTP://<SAS-URL>/v2.0/registration
It is possible to edit this and add/remove the end slash in the flaskServer.py itself in line 20

**Comment by idanrazisr** [comment]
The file "with_end_slash_flaskServer.py" is just an example file.
