### ISSUE TITLE
Mock-SAS v3.0: Object name "measReportConfig" should not be used in "CBRSrequestHandler/def handle_Http_Req"

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#37]
In "CBRSrequestHandler/def handle_Http_Req" function, "measReportConfig" appears in several places, after reading the code it seems that it tries to check if the measurement report is sent out in heartbeat request message. But according to Specification, "measReportConfig" will never be in the request message, it only appear in response message from SAS to CBSD. 

So over here the "measReportConfig" should be replaced by "measReport", because this is the one that appears in request message to represent measurement report information.

**Comment by idanrazisr** [comment]
Removed this code from Mock-SAS code uploaded 1-September-2017.  Mock-SAS code uploaded 1-September-2017 addresses "meas Report" according to section 11.9 in Mock-SAS tutorial “11.9      Handling of measReport in Request Messages”.

**Comment by ericzh31ericsson** [comment]
verified
