### ISSUE TITLE
TLS connection is not getting through between CBSD and Mock SAS, while using intermediate CA 

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#4]
Certificates created as follows:
CBSD: rootCA,  CBSD_intermediateCA,  CBSD_Endentity
SAS: rootCA, SAS_intermediateCA, SAS_Endentity

rootCA is common for both SAS and CBSD. 
1187	6.078225	172.19.61.243	172.19.61.36	TLSv1.2	231	Client Hello
1194	6.119177	172.19.61.36	172.19.61.243	TLSv1.2	1516	Server Hello
1196	6.119430	172.19.61.36	172.19.61.243	TLSv1.2	647	Certificate
Certificate (id-at-countryName=US,id-at-stateOrProvinceName=CA,id-at-localityName=Sunnyvale,id-at-organizationName=Ruckus Wireless,id-at-organizationalUnitName=Small Cell,id-at-commonName=SAS)
1199	6.120057	172.19.61.243	172.19.61.36	TLSv1.2	75	Alert (Level: Fatal, Description: Unknown CA)

SAS sent only end entity and as intermediate CA for SAS is different from CBSD intermediate CA. CBSD could not able to verify certificates of SAS server.
Wireshark log is attached here for reference.
[intermediateCA.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1161996/intermediateCA.zip)

**Comment by idanrazisr** [comment]
In the file cacertidan1.pem which has the Root CA, please put also the intermediate CA. So this pem file will look the following:
-----BEGIN CERTIFICATE-----
<string intermediate CA>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<string Root CA>
-----END CERTIFICATE-----

It may be that the order is important and Root CA needs to come before Intermediate CA

**Comment by awaizkhan** [comment]
Saurabh please try the recommended fix here in pem file and update the ticket.

**Comment by saudawar** [comment]
Tried the same, now MOCK SAS is sending proper cert chain to CBSD. But same has to be updated in certificate creation script, so that certs can be made as per the fix. So it will need changes to be made in certificate creation script.
