### ISSUE TITLE
Mock-SAS decoding of CPI Signed Data 

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#44]
Future Mock-SAS implementation will need to decode CPI Signed Data from Registration Request.
This is to provide some guidelines on how to do this in Python code.
To run the example code below you need to make sure that you have pyjwt installed by running:
pip install pyjwy

Example Python Code that does encoding and then decoding 

import jwt

payload = {
  "fccId": "Airspan-LTE44",
  "cbsdSerialNumber": "76B1E617472C",
  "installationParam": {
    "latitude": 26.3949,
    "longitude": -80.1002,
    "height": 73,
    "heightType": "AMSL",
    "horizontalAccuracy": 3,
    "verticalAccuracy": 3,
    "indoorDeployment": False,
    "antennaAzimuth": 0,
    "antennaDowntilt": 0,
    "antennaGain": 0,
    "eirpCapability": 0,
    "antennaBeamwidth": 0,
    "antennaModel": None
  },
  "professionalInstallerData": {
    "cpiId": "Airspan",
    "cpiName": "Airspan",
    "installCertificationTime": "2017-07-17T20:00:00Z"
  }
}

secret = 'secret'
jwt_message = jwt.encode(payload, secret)
print("Encoded message:")
print(jwt_message)
print("-------------")

decoded_payload = jwt.decode(jwt_message, secret)
print("Decoded message:")
print(decoded_payload)
print("-------------")

In this case I am decoding the payload myself, so it is not exactly the full flow required by Mock-SAS.

**Comment by idanrazisr** [comment]
I downloaded the JWT handobook from https://auth0.com/e-books/jwt-handbook
Section 4.2.2 gives the example with private/public keys of certificates by creating the PEM files and using them.

4.2.2 RS256: RSASSA + SHA256
Signing and verifying RS256 signed tokens is just as easy. The only difference lies in the use of
a private/public key pair rather than a shared secret. There are many ways to create RSA keys.
OpenSSL is one of the most popular libraries for key creation and management:
# Generate a private key
openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
# Derive the public key from the private key
openssl rsa -pubout -in private_key.pem -out public_key.pem
Both PEM files are simple text files. Their contents can be copied and pasted into your JavaScript
source files and passed to the jsonwebtoken library.
// You can get this from private_key.pem above.
const privateRsaKey = `<YOUR-PRIVATE-RSA-KEY>`;
const signed = jwt.sign(payload, privateRsaKey, {
algorithm: 'RS256',
expiresIn: '5s'
});
// You can get this from public_key.pem above.
const publicRsaKey = `<YOUR-PUBLIC-RSA-KEY>`;
const decoded = jwt.verify(signed, publicRsaKey, {
// Never forget to make this explicit to prevent
// signature stripping attacks.
algorithms: ['RS256'],
});

**Comment by cwilliams-ericsson** [comment]
Hi Idan,

V1.1.0 of SAS-CBSD Protocol spec states that signature should be based on HMAC SHA-256 algorithm.
The above info is for "RS256" signature, but the spec seems to call for "HS256" signature,

**Comment by cwilliams-ericsson** [comment]
V1.2.0 of SAS-CBSD Protocol now lists signature methods as: [ "RS256", "ES256" ].  This has been implemented in Test Harness.  Latest changes as of pull-request #77.

**Comment by idanrazisr** [comment]
CPI Signed Data implemented correctly in latest release. Closing issue.
