### ISSUE TITLE
Mock-SAS handling of Grant Renew in Heartbeat Request

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#45]
Mock-SAS current implementation is to take into consideration the Grant Renew in the Heartbeat Request message. If Grant Renew = TRUE then Mock-SAS will automatically return in the Heartbeat Response a new GrantExpireTime. Althogh Grant Renew is an optional parameter in Heartbeat Request, if it apperas only in the JSON Optional then Mock-SAS fails the Registration Request with error:
"Ihe server shot down because :  ERROR - loading optinal parameters not succeeddedobject of type 'bool' has no len()"
Mock-SAS issue is that it requires Grant Renew to appear in the JSON Expected file of the Heartbeat.
CBSD may or may not sent Grant Renew in Heartbeat Request, hence the bug in Mock-SAS.

**Comment by ericzh31ericsson** [comment]
Please verify again with the new branch submitted by Ericsson in Oct. 20th

**Comment by awaizkhan** [comment]
Idan can you please update?
