### ISSUE TITLE
<Branch for Oct. 20th #46> response code:103 for other procedure which are not defined in main JSON file

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#49]
Hi,

Response code:103 for other procedure which are not defined in main JSON file, is not seem to be a good option. Instead of this error code, it will be good if SAS does not respond to that other procedures. Because error code handling for 103 can be differ from vendor to vendor.

Regards,
Pawan Jangid

**Comment by cwilliams-ericsson** [comment]
Hi,

Not sure I understand the issue.  Could you please elaborate (or provide an example)?  Thanks!

**Comment by pawan25062** [comment]
hi,
According to step 4 defined in each case"WINNF-TS-0122-V0.0.0-r5.4 CBRS CBSD Test Specification", it is written that:

4 | After completion   of step 3, SAS Test Harness will not provide any further response messages to   UUT. | -- | --
-- | -- | -- | --

So SAS test harness should not respond any further messages to UUT.

**Comment by awaizkhan** [comment]
@pawan25062   can you please provide the test case number?

**Comment by pawan25062** [comment]
@awaizkhan this step is common for all test cases

**Comment by cwilliams-ericsson** [comment]
Changing definition in TS to so that Test Harness will not provide positive responses (responseCode = 0) after completion of test case, instead of no response at all.

**Comment by awaizkhan** [comment]
Hi Chris,
Still I think we need to ensure the all Test CSV files reflect the change to ensure the last step response time is very large?

**Comment by cwilliams-ericsson** [comment]
Updated with improved messaging handling between test cases (no longer responseCode 103 for all requests).
