### ISSUE TITLE
In Mock-SAS v2.0 Local time is used in Response Message

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#5]
In current Mock-SAS v2.0 code, the result of grantExpireTime and transmitExpireTime calculation is current local time, not UTC time which required in Specification. 

Check the code in CBRSRequestHandler. get_Expire_Time, it has “currentDateTime = DT.datetime.now()”, so might meed to change to “currentDateTime = DT.datetime.utcnow()”

**Comment by idanrazisr** [comment]
This issue is fixed as part of the CBRS_Mock_SAS_Python_Master uploaded on August 2nd 2017

**Comment by ericzh31ericsson** [comment]
It has been tested in Mock-SASv2.1
