### ISSUE TITLE
 CBRS_MOCK_SAS_V_2_0 could not start on centos

### ISSUE THREAD

**Issue by TedMore** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#50]
Hi,
Try to run  cbrs mock SAS on CentOS system, it is failure and prompts there is no config fiel conf.xml.
seem that this project can not run on linux. Could you help to check it? Thanks in advance.

[ute@localhost CBRS_MOCK_SAS_V_2_0]$ python /home/ute/Downloads/CBRS_MOCK_SAS_V_2_0/CBRS_MOCK_SAS_V_2_0/cbrsPython-master/cbrsPython/controllers/StartOfProject.py
Traceback (most recent call last):
  File "/home/ute/Downloads/CBRS_MOCK_SAS_V_2_0/CBRS_MOCK_SAS_V_2_0/cbrsPython-master/cbrsPython/controllers/StartOfProject.py", line 113, in <module>
    confFile= minidom.parse(current_path +"\conf.xml")
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1921, in parse
    return expatbuilder.parse(file)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 2] No such file or directory: '/home/ute/Downloads/CBRS_MOCK_SAS_V_2_0/CBRS_MOCK_SAS_V_2_0/cbrsPython-master/cbrsPython/controllers\\conf.xml'
[ute@localhost CBRS_MOCK_SAS_V_2_0]$

**Comment by cwilliams-ericsson** [comment]
Hi,
Currently, Test Harness code will only run under Windows, and will not run on Linux.  There is a feature for Linux support, but it is currently prioritized below other features, so no planned date yet.

**Comment by TedMore** [comment]
@cwilliams-ericsson , I see, thank you very much

**Comment by cwilliams-ericsson** [comment]
Linux support now available (see latest pull request)
