### ISSUE TITLE
channelType is missing from Grant Response

### ISSUE THREAD

**Issue by dgcell20** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#52]
channelType is missing from the Grant Response (using the Ericsson Oct 20 branch code)

**Comment by cwilliams-ericsson** [comment]
Test Harness uses channelType for grant response from jsonExpected file.  However, if it does not appear there, the Test Harness does not include it in the response.  Fix is as follows:

in CBRSRequestHandler.py, add following two lines...

    def processGrantResponse(self,jsonResponsedefined,httpRequest):
        
        if(jsonResponsedefined["response"]["responseCode"] ==0):
            if(self.grantId == 0) :
                self.grantId = str(randint(1, 1000000000))                
                self.assertion.grantId = self.grantId  
            self.change_Value_Of_Param_In_Dict(jsonResponsedefined, "grantId", self.grantId) 
            
            if(self.shorterGrantTime != True):                
                secondsToAdd = int(self.cbrsConfFile.getElementsByTagName("secondsToAddForGrantExpireTime")[0].firstChild.data)                          
            else:
                secondsToAdd = consts.SHORTER_GRANT_EXPIRY_TIME
            
            if (not 'channelType' in jsonResponsedefined):              ### Add this line
                jsonResponsedefined['channelType'] = 'GAA'            ### Add this line
                
            result = self.get_Expire_Time(secondsToAdd)
            ...

**Comment by awaizkhan** [comment]
@dgcell20  can you please retest and provide feedback so we can close this issue?

**Comment by dgcell20** [comment]
Validated
