### ISSUE TITLE
SAS test harness should not include cbsdId for non-zero response codes in REG response

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#54]
hi,

SAS test harness should not include cbsdId for non-zero response codes(e.g. 102,103,100,101,200,201 etc) in REG response.
According to test case document "WINNF-TS-0122-V0.0.0-r5.4 CBRS CBSD Test Specification.docx" it is defined that:

3 | SAS Test Harness   rejects the request by sending a CBSD Registration Response as follows:   -          SAS   response does not include cbsdId   -          The   responseCode in Response Object shall be 101. | -- | --
-- | -- | -- | --

**Comment by cwilliams-ericsson** [comment]
Here is a code work around:  in CBRSRequestHandler, def processResponse( ), replace the following code:
        elif(typeOfCalling == consts.REGISTRATION_SUFFIX_HTTP):
            if(self.cbsdId==None):
                self.cbsdId = httpRequest["fccId"]+ "Mock-SAS" + self.cbsdSerialNumber
                self.assertion.cbsdId = self.cbsdId
            self.change_Value_Of_Param_In_Dict(specificRespJson, "cbsdId", self.cbsdId)  

With the following code:

         elif(typeOfCalling == consts.REGISTRATION_SUFFIX_HTTP):
            if specificRespJson['response']['responseCode'] == 0:
                if(self.cbsdId==None):
                    self.cbsdId = httpRequest["fccId"]+ "Mock-SAS" + self.cbsdSerialNumber
                    self.assertion.cbsdId = self.cbsdId
                self.change_Value_Of_Param_In_Dict(specificRespJson, "cbsdId", self.cbsdId)
            elif 'cbsdId' in specificRespJson:
                del specificRespJson['cbsdId']

**Comment by pawan25062** [comment]
hi Chris, 

We have tried with workaround you have mentioned. But still we are getting CBSD id with non-zero response.
[WINNF.FT.C.REG.16_2017-11-08T13.20.59Z.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1454006/WINNF.FT.C.REG.16_2017-11-08T13.20.59Z.zip)
[CBRSRequestHandler.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1454009/CBRSRequestHandler.zip)

**Comment by cwilliams-ericsson** [comment]
Hi,

Your code change in CBRSRequestHandler.zip (you attached to previous comment) appears to be incorrect.  Check your indentation of the lines.  You did not indent the 7 lines under the elif (typeOfCalling == ..) statement.

Please check again.  Hopefully this will solve your problem.

**Comment by pawan25062** [comment]
hi,
Tried the same and it is working fine now.
