### ISSUE TITLE
registration request fails - URL not found

### ISSUE THREAD

**Issue by meitalk** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#56]
Hi,
After installing the latest MOCK SAS , I receive the following response when I sends the registration requests <https://XXXX:5000/v2.0/registration>:
Response data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>404 Not Found</title><h1>Not Found</h1><p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

The Mock SAS server URL is set correctly in the CBRS_MOCK_SAS_V_2_0\cbrsPython-master\Configuration\conf.
Actually, I copied the conf file from previous Mock SAS version , which worked fine, to the new Mock SAS version were I received the failure above. 
I would appreciate fast response.

**Comment by cwilliams-ericsson** [comment]
A couple of possibilities:
- url should include "v1.1", not "v2.0"
- possibly an issue with certificates between CBSD and Test Harness?
- Firewall or other issue on server?

**Comment by meitalk** [comment]
- When using v1.1 version, connection to the Mock SAS fails . 
- The certificates were taken from the github.
- firewall is off. 
The same server is able to connect and work properly with previous Mock SAS version.

**Comment by cwilliams-ericsson** [comment]
I assume this has been resolved and can be closed?
