### ISSUE TITLE
Handling for grant response with response code: 400/401

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#58]
Hi,
While creating JSON file for unsuccessful grant response test case 400/401, we are facing following issue:

Test case defined as:

3 | SAS Test Harness   sends a Grant Response message, including    ·           cbsdId=C   ·           responseCode = 400 | -- | --
-- | -- | -- | --

3 | SAS Test Harness   sends a Grant Response message, including   ·           cbsdId=C   ·           responseCode = 401 | -- | --
-- | -- | -- | --

So when we are implementing JSON file with just response code as 401 and no other parameter as follows :
"response":
        { 
		   "grantResponse":
		   [ 
		   	{
		    
		   	"response" : {"responseCode" : 400}
		    }
		   ]
   }
}

SAS test harness marking this test as FAIL with following error:
2017-11-09T11:58:31.322Z - INFO - engine sent successfully, the response to CBRS  : "heartbeatInterval"
2017-11-09T11:58:31.835Z - INFO - The final result of the test : WINNF.FT.C.GRA.1 is - FAIL

But if we try it putting  "heartbeatInterval" in main JSON file, this test case pass successfully. But we need not to have "heartbeatInterval"  in grant response as mentioned in step 3 for this test case.

log file is also attached here for more reference,.
[WINNF.FT.C.GRA.1_2017-11-09T11.58.23Z.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1457506/WINNF.FT.C.GRA.1_2017-11-09T11.58.23Z.zip)

**Comment by ericzh31ericsson** [comment]
This is the limitation of current Mock-SAS, it exists at day one, because it uses this value for other calculations. i.e. it will based on the pre-design json heartbeatInterval to calculate the heartbeat valid time. The good thing of this is the flexibility of Interval, but it becomes required element, another solution is make it a fix value in Mock-SAS, then it will not check if this value is in json or not. But all the test will use the same value. I will try to make it handles both if we decide both are needed.


Thanks


Eric

**Comment by ericzh31ericsson** [comment]
A quick fix has been submitted to GitHub, please download the file and try again.

Thanks


Eric

**Comment by pawan25062** [comment]
hi,
A quick fix has been submitted to GitHub, please download the file and try again.
>>> Could you please let us know, From where we need to download that file?

**Comment by ericzh31ericsson** [comment]
Still the branch of Ericsson-Submission-Nov03

**Comment by awaizkhan** [comment]
@pawan25062  can you please update if you have picked up the fix?

**Comment by pawan25062** [comment]
hi,
@ericzh31ericsson : could you please provide the updated site packages for "Ericsson-Submission-Nov03" branch?  

Because when we are running server it is giving following error:
![image](https://user-images.githubusercontent.com/31058265/33060768-6a7b3464-cebf-11e7-9032-828e68a35d8c.png)

**Comment by cwilliams-ericsson** [comment]
You will need to install (if not already installed), the python package:   ‘pyjwt’

**Comment by pawan25062** [comment]
@ericzh31ericsson we have tried installing python package "pyjwt".
But we are getting following error:
![image](https://user-images.githubusercontent.com/31058265/33074319-b94050c6-ceeb-11e7-8e33-896af4b8955e.png)

So we have try to install python package "pycrypto" also, but for this also we are getting following error:
![image](https://user-images.githubusercontent.com/31058265/33074372-f312e7e6-ceeb-11e7-92f5-560b84040e5c.png)

**Comment by cwilliams-ericsson** [comment]
Here is my full package installation (below).  There are items there you don't need for the Test Harness, but you could compare.  May need 'cryptography', if not present.

>python -m pip freeze
appdirs==1.4.3
asn1crypto==0.22.0
certifi==2017.11.5
cffi==1.10.0
chardet==3.0.4
click==6.7
cryptography==1.7.2
docopt==0.6.2
enum34==1.1.6
Flask==0.12
Flask-Testing==0.6.2
functools32==3.2.3.post2
idna==2.5
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.9.6
jsonschema==2.6.0
jwcrypto==0.4.2
MarkupSafe==1.0
packaging==16.8
pathlib==1.0.1
pipreq==0.4
pyasn1==0.3.7
pycparser==2.17
PyJWT==1.5.3
pyOpenSSL==17.0.0
pyparsing==2.2.0
requests==2.18.4
six==1.10.0
typing==3.5.3.0
urllib3==1.22
Werkzeug==0.12.2
yarg==0.1.9

**Comment by pawan25062** [comment]
@ericzh31ericsson if possible can you attach your site packages here or mail to me ?

**Comment by pawan25062** [comment]
hi,

Issue is resolved with this branch..
