### ISSUE TITLE
Relinquishment response from Mock SAS not defining "responseMessage"  correctly 

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#60]
Hi,

According to current handling:
11.6	Relinquishment Request as an Optional Procedure in the Test Sequence
Relinquishment Request may be an optional procedure for CBSD/Domain Proxy UUT prior to Deregistration Request. In this case a test case of [n.5] for Deregistration Request/Response may not mandate that CBSD/Domain Proxy UUT will send Relinquishment Request prior to Deregistration Request, however CBSD/Domain Proxy UUT does send Relinquishment Request. If the next step in the CSV file is “Deregistration” and “Relinquishment” does not appear as a step in the CSV file, Mock-SAS will accept a Relinquishment Request from CBSD/Domain Proxy UUT only if the Relinquishment Request is followed by the Deregistration Request. 

If we use .csv content as follows:
jsonFileName
HBT_registration_Cbsd1.json 
HBT_spectrumInquiry_Cbsd.json 
HBT_grant_Cbsd.json 
HBT_heartbeat_GrantedState.json 
HBT_heartbeat_Auth_Repeats.json
DRG_Success.json

And if we have relinquishment request sent by CBSD, then Mock SAS is responding as follows:
2017-11-14T07:23:26.551Z - INFO - engine sent successfully, the response to CBRS  : {
    "relinquishmentResponse": [
        {
            "cbsdId": "S9GQ710US01Mock-SAS401629000040", 
            "grantId": "782897439", 
            "response": {
                "responseCode": 0
            }, 
            "responseMessage": "NOT_SET this is from rel_In_Case_Of_Deregistration"
        }
    ]
}

Here "responseMessage" should be part of "response"parameter object.

**Comment by cwilliams-ericsson** [comment]
Added fix in currently open pull request.
Only changed file rel_In_Case_Of_Deregistration.json in jsonExpectedFolder (used to generate a response for optional relinquishment request), so should not otherwise impact code behaviour.

**Comment by pawan25062** [comment]
Yes... file is updated with correct syntax and values.
