### ISSUE TITLE
Last mock SAS server is LISTENING to local host only

### ISSUE THREAD

**Issue by meitalk** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#61]
Hi,
In the last Mock SAS version , the server is listening in port 5000 from localhost only, 127.0.0.1:5000.
This means the Mock SAS server cannot be accessed  from a server that is not local to Mock - SAS.

**Comment by ericzh31ericsson** [comment]
You should modify the ip address in config file according to your system.

**Comment by cwilliams-ericsson** [comment]
You should read tutorial and release notes on WINNF WG4 CBSD document repository for more details on how to setup and run the software.
