### ISSUE TITLE
MES_grant and MES_heartbeat JSON files in master folder need to be corrected

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#62]
Hi,

MES_grant and MES_heartbeat JSON files in master folder need to be corrected, as all files are defined with wrong syntax for "measReportConfig":

		   "grantResponse":
		   [ 
		   	{
		   	"heartbeatInterval" : 120.0,
    		"measReportConfig" : "RECEIVED_POWER_WITHOUT_GRANT",  		   	
		   	"response" : {"responseCode" : 0}
		    }
		   ]

**Comment by pawan25062** [comment]
hi, 

The files are still not corrected with "measReportConfig" correct syntax.
JSON files includes:
"measReportConfig" : "RECEIVED_POWER_WITHOUT_GRANT",

But it should be as follows:
"measReportConfig" : ["RECEIVED_POWER_WITHOUT_GRANT"],

**Comment by cwilliams-ericsson** [comment]
Fixed in latest pull-request #77 and #71.

Also added some additional fixes and reworking of the code for handling measReport in HBT messages, since some additional issues were found while testing fix for this issue.
