### ISSUE TITLE
Question for "WINNF.FT.C.HBT.9_HB_Resp_Absent_1stHB" need to be updated

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#67]
Hi,

Question for "WINNF.FT.C.HBT.9_HB_Resp_Absent_1stHB" need to be updated. 
Currently it ask for:
"Does cbsd UUT stop transmiting power after the Heartbeat response absent?"

But if HB response is absent for 1st HB which is in "GRANTED" state, then CBSD will not even start transmission.
So it should be:
"There were no RF transmissions from CBSD1 during the test?"

**Comment by awaizkhan** [comment]
You are right Pawan. I think we made a change in the specification as well to reflect this. Let's discuss on Wednesday morning call.

**Comment by cwilliams-ericsson** [comment]
Hi,

Already fixed in pull-request #59, as of commit on Friday, Nov 17 (commit: a321b0b).

Please confirm.

**Comment by pawan25062** [comment]
Yes .. the question is updated in this branch.
"Did cbsd UUT start transmission during test?"
