### ISSUE TITLE
the format "measCapability" data in OptionalParams.registrationOptional.json is not correct

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#8]
There is a wrong format in the data of measCapability  in OptionalParams.registrationOptional.json. In current Mock-SAS code, it is

      "measCapability":  {"$or":["EUTRA_CARRIER_RSSI_NON_TX","EUTRA_CARRIER_RSSI_ALWAYS"]},

When Mock-SAS processes the json data, if optional parameter "measCapability" is needed to add, then the result of json data will be a string. But according spec this data should be an array of string, i.e. should be a list format. So an error will happen when compare actual and expected json, The request from CBSD should be "measCapability":  ["EUTRA_CARRIER_RSSI_NON_TX"], but processed OptionalParams will be "measCapability":  "EUTRA_CARRIER_RSSI_NON_TX". 

Modified code to:

      "measCapability":  {"$or":[["EUTRA_CARRIER_RSSI_NON_TX"],["EUTRA_CARRIER_RSSI_ALWAYS"]]} 

fixed the issue.

**Comment by idanrazisr** [comment]
Only the example JSON file was not correct. Need to write the JSON file according to the new format described in this issue.

**Comment by ericzh31ericsson** [comment]
It is verified in Mock-SASv2.1
