### ISSUE TITLE
Grouping Params is rejected by Mock-SAS

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#80]
Perfroming Registration Request message which includes groupParam IE is rejected by Mock-SAS with the message:
for the CBRS with the cbsdSerialNumber :78A1E7174708 ERROR - loading optional parameters not succeeded- some parameters in http request are not defined by Specifications or bad names

**Comment by cwilliams-ericsson** [comment]
Hi Idan, can you post a log for this case?  I'd like to understand what is going on.

**Comment by cwilliams-ericsson** [comment]
Seems to be a mismatch between specification and laterDefinedOptional.json file defining grouping parameters.

Spec says "groupingParam" is array of object GroupParam.
Schema definition uses "groupParam" as object name.

So sending "groupingParam" in REG message will fail the schema check. I think this is the problem.

**Comment by cwilliams-ericsson** [comment]
Fixed in pull-request #77.

**Comment by idanrazisr** [comment]
validated correct behaviour with latest release. Closing issue.
