### ISSUE TITLE
Mock-SAS for test WINNF.FT.D.REG.4 accepts CAT B devices

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#81]
Test title WINNF.FT.D.REG.4 in Winnforum 122 document is for CAT A CBSDs. However Mock-SAS accepts in Registration Request also CAT B CBSDs for this test case.

**Comment by cwilliams-ericsson** [comment]
Can this be solved by adding "cbsdCategory": "A" in the expected json file for this test case?

I think this is the simplest solution.

**Comment by cwilliams-ericsson** [comment]
Fixed in pull-request #77

**Comment by idanrazisr** [comment]
Issue fixed in latest release. Closing issue.
