### ISSUE TITLE
Mock-SAS for WINNF.FT.D.REG.4 accepts also CPI signed Data IE in Registration Request

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#82]
Test title of WINNF.FT.D.REG.4 in WiNNF 122 document is for CAT A without CPI signed data.
But if the CPI signed data is included when running this test case the Mock-SAS attempts to decode instead of failing the test. the selected test from the user : WINNF.FT.D.REG.4 is starting now
2017-12-15T08:28:25.584000Z: CBSD sent registration Request from the address : 90.0.0.27
cpiSignatureData signature error: The specified alg value is not allowed
2017-12-15T08:28:26Z: validation passed successfully, the engine sent registration Response
The final result of the test : WINNF.FT.D.REG.4 is - FAIL

**Comment by cwilliams-ericsson** [comment]
Agree.  Since this is limited to a small number of registration test cases, need a method, probably in json file to ban use of CPI-data for REG.3 and REG.4 test cases.

Similarly, currently I think there is no stopping a CBSD from putting cpiSignatureData AND installationParam in the same registration message.  May need to fix that case as well.

**Comment by dgcell20** [comment]
The final result is a FAIL which is appropriate.
Or you suggesting that Test Harness should fail the test prior to getting to the point of decoding the signed data?

If the vendor knows their device will send CPI signed data then should they instead be executing WINNF.FT.C.REG.5 or WINNF.FT.D.REG.6 test cases (listed as C3: Mandatory for UUT which supports single-step registration containing CPI-signed data in the registration message)?

WINNF.FT,C.REG.3 and WINNF.FT.D.REG.4 are listed as C2: Mandatory for UUT which supports single-step registration with no CPI-signed data in the registration message.

**Comment by cwilliams-ericsson** [comment]
We could add a check:  if cpiSignatureData and installationParam exist in same registration message, then fail the CBSD.  This would handle all the cases (cpiSignatureData in REG.3 and REG.4, or installationParam in REG.5 and REG.6).

This is based on notion that SAS will fail registration if this occurs.

Any comments?

**Comment by cwilliams-ericsson** [comment]
Added check for cpiSignatureData and installationParam in the same registration message.

Fixed in latest pull-request (#77 and #71 )

**Comment by idanrazisr** [comment]
Verified correct behaviour with latest release. Closing issue.
