### ISSUE TITLE
Naming convention for HBT test cases

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#83]
Current Heartbeat CSV files in Mock-SAS testfiles folder have additional text after the title from the Winnforum 122 document. Other CSV files (REG,RLQ, etc) are keeping the format of the title only.

**Comment by cwilliams-ericsson** [comment]
Agree.
Will update in pull-request.

**Comment by cwilliams-ericsson** [comment]
Updated names in Pull-Request #77

**Comment by idanrazisr** [comment]
Verified correct naming convention in latest release. Closing issue.
