### ISSUE TITLE
Mock-SAS shows double Information for Heartbeat Intervals 

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#84]
Running RLQ test cases with HeartbeatRepeats the Mock-SAS shows double Information for Heartbeat Intervals 
2017-12-15T10:38:45.861Z - INFO - The time interval between two heartbeat request messages is 30.277
2017-12-15T10:38:45.861Z - INFO - The time interval between two heartbeat request messages is 0.0

**Comment by idanrazisr** [comment]
This occurs running RLQ and DRG test cases with Airspan Domain Proxy. For the HBT test case where Heratbeat Repeats JSON was NOT used the time interval Heartbeat was shown correctly.

**Comment by cwilliams-ericsson** [comment]
Fixed in Pull Request #77 and cloned to Pull Request #71

**Comment by idanrazisr** [comment]
verified correct behaviour in latest release. Closing issue.
