### ISSUE TITLE
Wrong implementation JSON file for WINNF.FT.D.DRG.4 test case

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#85]
Wrong implementation JSON file for WINNF.FT.D.DRG.4 test case that causes Mock-SAS not to execute the test properly.
Error in JSON Expected file DRG_error_102.json. "deregistrationResponse" : comma after 102 exists by mistake:
    [
     {
       "response": {
       "responseCode": 102,
       }
     }
    ]  
   }

**Comment by cwilliams-ericsson** [comment]
Fixed in Pull-Request #77

**Comment by idanrazisr** [comment]
Verified correct behaviour with latest release. Closing issue.
