### ISSUE TITLE
Issues in registrationOptional.json file

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#9]
There are two issues existing in OptionalParams/registrationOptional.json which caused the test failure in Ericsson system. 

The first problem is the structure of object "installationParam" is not accepted by json comparison in Mock-SAS v2.0. The original registrationOptional.json is below:

    "name":"Registration_1_2_3_4",  
			"registrationOptionalParams":
        	[
            	{
				  "airInterface": { "radioTechnology": "lte", "supportedSpec": "lte-rel10" },
				  "cbsdCategory": {"$or":["Addd","Bddd"]},
				  "measCapability":  {"$or":["EUTRA_CARRIER_RSSI_NON_TX","EUTRA_CARRIER_RSSI_ALWAYS"]},
				  "radioTechnology": "E_UTRA",
				  "supportedSpec": "FFS",
				  "latitude": "${range:-90.00000To90.00000}",
				  "longitude": "${range:-180.000000To180.000000}",
				  "heightType": {"$or":["AGL","AMSL"]},
				  "horizontalAccuracy":"${range:0To50}",
				  "verticalAccuracy":"${range:0To3}",
				  "indoorDeployment":{"$or":["True","False"]},
				  "antennaAzimuth":"${range:0To360}",
				  "antennaDowntilt":"${range:-90To90}",
				  "antennaGain":"${range:-127To128}",
				  "eirpCapability":"${range:-127To47}",
				  "antennaBeamwidth":"${range:0To360}",
				  "antennaModel":"${maximumLength:128}"
				}
			]	

When parsed the json data, it expected the key of "installationParam", but it is not here even all the parameters of "installationParam" are listed already. By adding "installationParam" and reorganized the data structure, Mock-SAS can parse the json data. 

Another issue in installationParam is that it missing parameter **"height"**. The test will be failed if CBSD sends out this parameter. 

So after modified registrationOptional.json as below  the test with OptionalParams in registration test can work as expected..

{
    "name":"Registration_1_2_3_4",  
	"registrationOptionalParams":
        	[
            	{
				  "callSign" : "not available",
				  "airInterface": { "radioTechnology": "E_UTRA", "supportedSpec": "FFS" },
				  "cbsdCategory": {"$or":["A","B"]},
				  "measCapability":  {"$or":[["EUTRA_CARRIER_RSSI_NON_TX"],["EUTRA_CARRIER_RSSI_ALWAYS"]]},
				  "installationParam":{
					  "latitude": "${range:-90.00000To90.00000}",
					  "longitude": "${range:-180.000000To180.000000}",
					  "height": "${range:0To300}",
					  "heightType": {"$or":["AGL","AMSL"]},
					  "horizontalAccuracy":"${range:0To50}",
					  "verticalAccuracy":"${range:0To3}",
					  "indoorDeployment":{"$or":["True","False"]},
					  "antennaAzimuth":"${range:0To360}",
					  "antennaDowntilt":"${range:-90To90}",
					  "antennaGain":"${range:-127To128}",
					  "eirpCapability":"${range:-127To47}",
					  "antennaBeamwidth":"${range:0To360}"},
				  "cbsdInfo" : {"vendor" : "Ericsson", "model" : "KRC 161 606/1"}
				}
			]	
}

**Comment by ericzh31ericsson** [comment]
Adding "registrationOptionalParams" is just a workaround, it only solved the value range flexibility. There is a limitation that the parameters items inside "registrationOptionalParams" has to be exactly same as what in the incoming request message. any inconsistency between them will cause the error. 

This issue is also existing in other parameters, for example of "operationParam".

**Comment by idanrazisr** [comment]
This issue is fixed as part of the CBRS_Mock_SAS_Python_Master uploaded on August 2nd 2017

**Comment by ericzh31ericsson** [comment]
it is closed.
