### ISSUE TITLE
WINNF.FT.C.REG.7 failed to run

### ISSUE THREAD

**Issue by gapelbaum** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#94]
Hi,

Test WINNF.FT.C.REG.7 failed to run because required a JSON (REG_Success_cbsd1.json) that not exist.

Gustavo

**Comment by dgcell20** [comment]
In WINNF.FT.C.REG.7.csv change REG_Success_cbsd1.json to REG_MultiStep_Success_cbsd1.json.

**Comment by gapelbaum** [comment]
That what I did, but need to fix the file in the main branch.

**Comment by cwilliams-ericsson** [comment]
Fixed as per dgcell20 comment above, committed to branches: bug-fixes-2018-January, Linux-support-branch.

**Comment by cwilliams-ericsson** [comment]
I assume this has been resolved and can be closed?
