### ISSUE TITLE
WINNF.FT.C.REG.1

### ISSUE THREAD

**Issue by dgcell20** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#95]
There is only one line in the log file.
2018-01-08T07:09:00.344Z - INFO - the selected test from the user : WINNF.FT.C.REG.1 is starting now

Added the following to registrationOptional.json file and test then ran.
  "airInterface": {
    "type": "object",
    "description": "Air interface parameter for a CBSD",
  "required": [ "radioTechnology"],    
    "properties": {
    "radioTechnology": { "enum": [ "E_UTRA" ],
                    "description": "Registered with the Wireless Innovation Forum for operation in the CBRS band." }
         }
     }

Not sure why this information was not being obtained from the laterDefinedOptional.json file.

**Comment by dgcell20** [comment]
Not sure exactly the issue, but using latest master branch code, the previous issue was not encountered.

**Comment by cwilliams-ericsson** [comment]
I am not seeing the same problem.  Tried running with latest branch: 'bug-fixes-2018-January', and also: 'Linux-support-branch'.

I have run the following test cases with WINNF.FT.C.REG.1:
- REG request has proper radioTechnology value -- test pass
- REG request has no airInterface object -- test pass
- REG request has airInterface value which is not one of the enumerated types -- test fail

It would be useful to get the log of your test which fails -- I'm not able to reproduce.

I also suggest you get the latest code GitHub, if you are not already running, just in case.
