### ISSUE TITLE
Tests WINNF.FT.D.HBT.8 not exist

### ISSUE THREAD

**Issue by gapelbaum** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#96]
Hi,

Someone know is there this test case and where I can found it.

Gustavo

**Comment by dgcell20** [comment]
I can see WINNF.FT.D.HBT.8 located in the cbrsPython-master\testFiles directory.

**Comment by cwilliams-ericsson** [comment]
Please check your setup or get latest updates from GitHub.  The test is there!

Let me know if that does not solve the issue.

**Comment by cwilliams-ericsson** [comment]
I assume this has been resolved and can be closed?

**Comment by gusapleton** [comment]
Yes, you can close it
