### ISSUE TITLE
Test WINNF.PT.C.HBT not found

### ISSUE THREAD

**Issue by gapelbaum** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#97]
Hi,

Not found this test in the test folder, is it under construction ?

Gustavo

**Comment by dgcell20** [comment]
The Transmit power measurement test case, WINNF.PT.C.HBT.1, requires a separate script to be executed to support the unique heartbeat required for this test case
Use “StartPowerMeas.py” to start this test case.  User is prompted for:
•	start frequency (fs),
•	bandwidth (BW), and 
•	maxEirp (P) for the test case.

**Comment by cwilliams-ericsson** [comment]
I assume this has been resolved and can be closed?

**Comment by gusapleton** [comment]
Yes, close it
