### ISSUE TITLE
MockSAS  on clear channel - without encryption

### ISSUE THREAD

**Issue by gapelbaum** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#98]
Hi,

Is it possible to run MockSAS without traffic encryption (over http without ssl) ?

The intention is to sniff the messages on test mode.

Gus

**Comment by cwilliams-ericsson** [comment]
I think you can do this by modifying  flaskServer.py as follows (last line in the file) to avoid using the sslcontext.  Change this:

`def runFlaskServer(host,port,ctx):
    app.run(host,port,threaded=True,request_handler=WSGIRequestHandler,ssl_context=ctx)`

to this (remove 'ssl_context=ctx'):

`def runFlaskServer(host,port,ctx):
    app.run(host,port,threaded=True,request_handler=WSGIRequestHandler)`

Let me know how it goes.

**Comment by cwilliams-ericsson** [comment]
Sorry, seems like email has format of code change a bit confused.  Don't change format of last line, just remove the ssl_context.
