### ISSUE TITLE
Mock-SAS will get stuck if test does not reach the questions phase 

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#99]
Testing with latest Mock-SAS branch "bug-fixes-2018-January" I can see the following behaviour:
As long as the CBSD/DP UUT follows the steps in the CSV file and the engine reaches the question phase, then the engine is OK and you can activate the next test from Command Prompt.
However, if the test failed in the middle for any reason: CBSD/DP UUT sent a wrong Request message not according to the required sequence, Request message had wrong parameter, wrong CBSD serial number in the XML Confiugration file then:
1) Mock-SAS immediately stops the test and says "test FAIL" --> this is correct behaviour from Mock-SAS validating the Request messages and sequence
2) Mock-SAS says "Please enter a csv file path that includes..." to select the next test --> this is correct behaviour from Mock-SAS to select the next test.
When the user now selects a new test to run (writing a new "WINNF.FT...." in the Command Prompt, then it looks like Mock-SAS is OK and starting the test but effectively Mock-SAS doesn't see any messages coming from CBSD/DP UUT. 
At this point CTRL-C does not work and the only way out is to completely close the Command Prompt and open the command prompt again.
The workaround here is that if Mock-SAS fails the test and does NOT reach the questions phase, then:
1) When Mock-SAS says "Please enter a csv file path that includes..." to select the next test, PRESS CTRL-C in order to stop Mock-SAS.
2) run again StartOfProject.py to reactivate Mock-SAS.
At least with this workaround the user will not get stuck and no need to close the entire Command Prompt as a last option to get out.

**Comment by cwilliams-ericsson** [comment]
Please check with fix provided in working branch.  Bypass shutdown of Werkzeug server if "server shot down", to allow running further test cases.

**Comment by idanrazisr** [comment]
Verified correct behaviour of this fix on master branch 15-feb-2018. 
The Command Prompt will continue to display incomoing messages from UUT after the FAIL.
But the user can enter properly the next test name WINNF.FT.XXXX and the Test Harness will continue properly. Closing issue.
